# Generated by tools/gen_lookml.py. Do not edit by hand.
# Every value below is a PLACEHOLDER mirroring a key in .env and must be
# filled in before deploying. Nothing in this repo
# connects to anything until they are real.

constant: connection_name {
  # Name of the BigQuery connection configured inside the Looker instance.
  # Mirrors LOOKER_BQ_CONNECTION in .env (currently 'censo_anual_bq' in .env).
  value: "daisy_migration_connection"
}

constant: gcp_project {
  # GCP project hosting the mart dataset.
  # Mirrors GCP_PROJECT_ID in .env (currently 'REPLACE_ME' in .env).
  value: "poc-bankinter-snow"
}

constant: dataset_mart {
  # Dataset holding the 5 mart relations dbt builds (R1.1).
  # Mirrors BQ_DATASET_MART in .env (currently 'iaest_censo_mart' in .env).
  value: "obiee_bq_core"
}
