view: dim_pais {
  # Generated by tools/gen_lookml.py from migration/ir/model.json.
  # Do not edit by hand; edit the generator or the IR.
  # Binds to the dbt mart relation `dim_pais` (RULEBOOK R1.1).
  sql_table_name: `@{gcp_project}.@{dataset_mart}.dim_pais` ;;
  # Dimensions, dimension_groups and drill sets — RULEBOOK R5, R7, R8.
  # view_label mirrors the OBIEE presentation folder that exposes each field
  # (R8.5); a logical column no folder exposes is hidden — it is plumbing.
  dimension: pais_clave {
    label: "PAIS_CLAVE"
    type: number
    sql: ${TABLE}.pais_clave ;;
    primary_key: yes
    hidden: yes
    description: "Surrogate join key (R6.4). primary_key is the fanout guard that lets Looker skip symmetric aggregates (R6.2)."
  }
  dimension: nacionalidad_pais_codigo {
    label: "Nacionalidad país código"
    type: string
    sql: ${TABLE}.pais_codigo ;;
    view_label: "Nacionalidad"
    description: "Sentinel pais_codigo = '108' means España — the nationality split hinges on it — a real member, not missing data (RULEBOOK R5.1)."
  }
  dimension: nacionalidad_pais_nombre {
    label: "Nacionalidad país nombre"
    type: string
    sql: ${TABLE}.pais_nombre ;;
    view_label: "Nacionalidad"
  }
  dimension: nacionalidad_pais_nombre_m {
    label: "Nacionalidad país nombre M"
    type: string
    sql: ${TABLE}.pais_iso ;;
    view_label: "Nacionalidad"
  }
  dimension: nacionalidad_area_codigo {
    label: "Nacionalidad área código"
    type: string
    sql: ${TABLE}.area_codigo ;;
    view_label: "Nacionalidad"
  }
  dimension: nacionalidad_area_nombre {
    label: "Nacionalidad área nombre"
    type: string
    sql: ${TABLE}.area_nombre ;;
    view_label: "Nacionalidad"
  }
  dimension: nacionalidad_continente_codigo {
    label: "Nacionalidad continente código"
    type: string
    sql: ${TABLE}.continente_codigo ;;
    view_label: "Nacionalidad"
  }
  dimension: nacionalidad_continente_nombre {
    label: "Nacionalidad continente nombre"
    type: string
    sql: ${TABLE}.continente_nombre ;;
    view_label: "Nacionalidad"
  }
  dimension: tipo_nacionalidad {
    label: "Tipo de nacionalidad"
    type: string
    sql: CASE WHEN ${TABLE}.pais_codigo = '108' THEN 'Española' ELSE 'Extranjera' END ;;
    view_label: "Nacionalidad"
    description: "OBIEE expression: CASE WHEN Nacionalidad país código = '108' THEN 'Española' ELSE 'Extranjera' END. Sentinel pais_codigo = '108' means España — the nationality split hinges on it — a real member, not missing data (RULEBOOK R5.1)."
  }
  dimension: fecha_inicio {
    label: "Fecha inicio"
    type: date
    sql: ${TABLE}.fecha_ini ;;
    datatype: date
    view_label: "Nacionalidad"
    hidden: yes
    description: "Unpopulated SCD column: FECHA_INI is 01/01/01 on 7,377 rows and every FECHA_FIN is 01/01/00. Parsed faithfully, hidden rather than exposed as junk (R8.2)."
  }
  dimension: fecha_fin {
    label: "Fecha fin"
    type: date
    sql: ${TABLE}.fecha_fin ;;
    datatype: date
    view_label: "Nacionalidad"
    hidden: yes
    description: "Unpopulated SCD column: FECHA_INI is 01/01/01 on 7,377 rows and every FECHA_FIN is 01/01/00. Parsed faithfully, hidden rather than exposed as junk (R8.2)."
  }
  dimension: actual {
    label: "Actual"
    type: number
    sql: ${TABLE}.actual ;;
    view_label: "Nacionalidad"
  }
  # R7.2 — drill chain Nacionalidad continente nombre → Nacionalidad área nombre → Nacionalidad país nombre.
  # Default chain on the measures.
  set: drill_pais {
    fields: [nacionalidad_continente_nombre, nacionalidad_area_nombre, nacionalidad_pais_nombre]
  }
}
