view: dim_sexo {
  # Generated by tools/gen_lookml.py from migration/ir/model.json.
  # Do not edit by hand; edit the generator or the IR.
  # Binds to the dbt mart relation `dim_sexo` (RULEBOOK R1.1).
  sql_table_name: `@{gcp_project}.@{dataset_mart}.dim_sexo` ;;
  # Dimensions, dimension_groups and drill sets — RULEBOOK R5, R7, R8.
  # view_label mirrors the OBIEE presentation folder that exposes each field
  # (R8.5); a logical column no folder exposes is hidden — it is plumbing.
  dimension: dimension_key {
    label: "DIMENSION_KEY"
    type: number
    sql: ${TABLE}.dimension_key ;;
    primary_key: yes
    hidden: yes
    description: "Surrogate join key (R6.4). primary_key is the fanout guard that lets Looker skip symmetric aggregates (R6.2)."
  }
  dimension: sexo_codigo {
    label: "Sexo (código)"
    type: string
    sql: ${TABLE}.codigo ;;
    view_label: "Edad y Sexo"
  }
  dimension: sexo {
    label: "Sexo"
    type: string
    sql: ${TABLE}.descripcion ;;
    view_label: "Edad y Sexo"
  }
  # R7.2 — drill chain Sexo.
  # Default chain on the measures.
  set: drill_sexo {
    fields: [sexo]
  }
}
