view: dim_edad {
  # Generated by tools/gen_lookml.py from migration/ir/model.json.
  # Do not edit by hand; edit the generator or the IR.
  # Binds to the dbt mart relation `dim_edad` (RULEBOOK R1.1).
  sql_table_name: `@{gcp_project}.@{dataset_mart}.dim_edad` ;;
  # Dimensions, dimension_groups and drill sets — RULEBOOK R5, R7, R8.
  # view_label mirrors the OBIEE presentation folder that exposes each field
  # (R8.5); a logical column no folder exposes is hidden — it is plumbing.
  dimension: dimension_key {
    label: "DIMENSION_KEY"
    type: number
    sql: ${TABLE}.dimension_key ;;
    primary_key: yes
    hidden: yes
    description: "Surrogate join key (R6.4). primary_key is the fanout guard that lets Looker skip symmetric aggregates (R6.2)."
  }
  dimension: edad_anno_anno {
    label: "Edad (año a año)"
    type: number
    sql: ${TABLE}.edad ;;
    view_label: "Edad y Sexo"
    description: "Sentinel edad = -1 means Desconocido/a — a real member, not missing data (RULEBOOK R5.1, R5.3)."
  }
  dimension: edad_hasta_95 {
    label: "Edad (hasta 95)"
    type: string
    sql: CASE WHEN ${TABLE}.edad >= 95 THEN '95 y más' WHEN ${TABLE}.edad < 10 THEN CONCAT('0', CAST(${TABLE}.edad AS STRING)) ELSE CAST(${TABLE}.edad AS STRING) END ;;
    view_label: "Edad y Sexo"
    description: "OBIEE expression: CASE WHEN EDAD >= 95 THEN '95 y más' WHEN EDAD < 10 THEN CONCAT('0', CAST(EDAD AS VARCHAR(10))) ELSE CAST(EDAD AS VARCHAR(10)) END. Sentinel edad = -1 means Desconocido/a — a real member, not missing data (RULEBOOK R5.1, R5.3)."
  }
  dimension: edad_grupos_quinquenales {
    label: "Edad (grupos quinquenales)"
    type: string
    sql: ${TABLE}.grupos_quinquenales ;;
    view_label: "Edad y Sexo"
  }
  dimension: edad_grandes_grupos {
    label: "Edad (grandes grupos)"
    type: string
    sql: ${TABLE}.grandes_grupos ;;
    view_label: "Edad y Sexo"
  }
  # R9.6 — port of the OBIEE presentation variable V_EDAD, set by the prompt `Petición de datos - Variable_Edad`. See docs/RULEBOOK.md R9.6.
  # The parameter holds the choice; the two yesno dimensions below are how a dashboard tile reads it.
  parameter: edad_variable {
    label: "Mostrar edad"
    type: string
    default_value: "Grupo quinquenal"
    view_label: "Edad y Sexo"
    description: "OBIEE presentation variable V_EDAD (prompt `Variable_Edad`). Default ported from the prompt's promptDefaultValues (R9.6)."
    allowed_value: {
      label: "Grupo quinquenal"
      value: "Grupo quinquenal"
    }
    allowed_value: {
      label: "Grupo grande"
      value: "Grupo grande"
    }
  }
  dimension: mostrar_grupo_quinquenal {
    label: "Mostrar Grupo quinquenal"
    type: yesno
    sql: {% parameter edad_variable %} = 'Grupo quinquenal' ;;
    view_label: "Edad y Sexo"
    group_label: "Mostrar edad (V_EDAD)"
    description: "OBIEE: FILTER 'Grupo quinquenal' IN V_EDAD — the analysis reading it returns rows only when the prompt is set to 'Grupo quinquenal' (R9.6). Not hidden: a dashboard tile filters on it, and Looker rejects a reference to a hidden field at validation."
  }
  dimension: mostrar_grupo_grande {
    label: "Mostrar Grupo grande"
    type: yesno
    sql: {% parameter edad_variable %} = 'Grupo grande' ;;
    view_label: "Edad y Sexo"
    group_label: "Mostrar edad (V_EDAD)"
    description: "OBIEE: FILTER 'Grupo grande' IN V_EDAD — the analysis reading it returns rows only when the prompt is set to 'Grupo grande' (R9.6). Not hidden: a dashboard tile filters on it, and Looker rejects a reference to a hidden field at validation."
  }
  # R7.2 — drill chain Edad (grandes grupos) → Edad (grupos quinquenales) → Edad (año a año).
  # Default chain on the measures.
  set: drill_edad {
    fields: [edad_grandes_grupos, edad_grupos_quinquenales, edad_anno_anno]
  }
}
