view: fct_censo_anual {
  # Generated by tools/gen_lookml.py from migration/ir/model.json.
  # Do not edit by hand; edit the generator or the IR.
  # Binds to the dbt mart relation `fct_censo_anual` (RULEBOOK R1.1).
  sql_table_name: `@{gcp_project}.@{dataset_mart}.fct_censo_anual` ;;
  # Dimensions, dimension_groups and drill sets — RULEBOOK R5, R7, R8.
  # view_label mirrors the OBIEE presentation folder that exposes each field
  # (R8.5); a logical column no folder exposes is hidden — it is plumbing.
  #
  # No primary_key: the fact's key is anno_censo, dim_pais_nacionalidad, dim_territorio_residencia, dim_sexo, dim_edad (5-column PK). R6.2 puts primary_key on
  # the dimensions, which are the `one` side of all 4 joins (R6.1) — that is
  # what lets Looker skip symmetric aggregates.
  # R6.4 — the 4 surrogate join keys the explore's `sql_on` binds to. They are
  # physical columns, not RPD logical columns, so they carry no OBIEE caption and
  # no label. Hidden: a join key is plumbing, not a user-facing field (R8.5).
  dimension: dim_sexo {
    type: number
    sql: ${TABLE}.dim_sexo ;;
    hidden: yes
    description: "Surrogate foreign key to dim_sexo, declared by the RPD as FACT_CENSO_ANU_AGG_PIRAMIDE_Clave Ajena -> DIM_SEXO_CENSO_ANUAL. The join is many_to_one and dim_sexo carries primary_key, which is what guards fanout (R6.1, R6.2, R6.4)."
  }
  dimension: dim_pais_nacionalidad {
    type: number
    sql: ${TABLE}.dim_pais_nacionalidad ;;
    hidden: yes
    description: "Surrogate foreign key to dim_pais, declared by the RPD as FACT_CENSO_ANU_AGG_PIRAMIDE_Clave Ajena#1 -> DIM_PAIS_NACIONALIDAD_CENSO_ANUAL. The join is many_to_one and dim_pais carries primary_key, which is what guards fanout (R6.1, R6.2, R6.4)."
  }
  dimension: dim_edad {
    type: number
    sql: ${TABLE}.dim_edad ;;
    hidden: yes
    description: "Surrogate foreign key to dim_edad, declared by the RPD as FACT_CENSO_ANU_AGG_PIRAMIDE_Clave Ajena#2 -> DIM_EDAD_CENSO_ANUAL. The join is many_to_one and dim_edad carries primary_key, which is what guards fanout (R6.1, R6.2, R6.4)."
  }
  dimension: dim_territorio_residencia {
    type: number
    sql: ${TABLE}.dim_territorio_residencia ;;
    hidden: yes
    description: "Surrogate foreign key to dim_territorio, declared by the RPD as FACT_CENSO_ANU_AGG_PIRAMIDE_Clave Ajena#3 -> DIM_TERRITORIO_RESIDENCIA_CENSO_ANUAL. The join is many_to_one and dim_territorio carries primary_key, which is what guards fanout (R6.1, R6.2, R6.4)."
  }
  dimension: anno_censo {
    label: "Año Censo"
    type: number
    sql: ${TABLE}.anno_censo ;;
    view_label: "Fecha Referencia Censo"
  }
  # R8.3 / DEV-DATE. In OBIEE this column is a *string*:
  #   '01/01/' || CAST(Año Censo AS CHARACTER(4))
  # mart.fct_censo_anual materializes a real DATE alongside the literal, so
  # Looker gets working timeframes and the parity check keeps its bytes.
  dimension_group: fecha_censo {
    label: "Fecha Censo"
    type: time
    timeframes: [raw, date, month, quarter, year]
    datatype: date
    sql: ${TABLE}.fecha_censo ;;
    view_label: "Fecha Referencia Censo"
    description: "DEV-DATE: OBIEE builds this as the string '01/01/' || CAST(Año Censo AS CHARACTER(4)). dbt materializes DATE(anno_censo, 1, 1) so Looker gets timeframes; fecha_censo_texto keeps the literal (R8.3)."
  }
  dimension: fecha_censo_texto {
    label: "Fecha Censo (texto OBIEE)"
    type: string
    sql: ${TABLE}.fecha_censo_texto ;;
    view_label: "Fecha Referencia Censo"
    description: "OBIEE's literal '01/01/' || CAST(Año Censo AS CHARACTER(4)), preserved for byte-level parity. Use the fecha_censo timeframes to filter (R8.3)."
  }
}
