view: +dim_territorio {
  # Generated by tools/gen_lookml.py from migration/ir/model.json.
  # Do not edit by hand; edit the generator or the IR.
  # Refinement of `dim_territorio` (views/base_views/dim_territorio.view.lkml): the measures - RULEBOOK R2, R3, R4.
  measure: superficie_municipio {
    # R4.1/R4.2 — `sum_distinct` keyed at the municipio level (municipio_codigo), never dimension_key.
    # R4.6 — reads the pre-guarded mart column. The sentinel is nulled row-level in
    # dbt, one step before any aggregation, so this file carries no sentinel handling
    # at all — which is what makes R4.4's misplacement bug unexpressible here.
    description: "Guarded denominator: area sentinels -1 and 0 are removed row-level in mart.dim_territorio — RULEBOOK R4.1, R4.2, R4.3 (null), R4.6"
    type: sum_distinct
    sql_distinct_key: ${TABLE}.municipio_codigo ;;
    sql: ${TABLE}.municipio_superficie_km2 ;;
    value_format_name: decimal_0
    hidden: yes
  }
  measure: superficie_municipio_raw {
    # R4.1/R4.2 — `sum_distinct` keyed at the municipio level (municipio_codigo), never dimension_key.
    # R4.6 — reads the pre-guarded mart column. The sentinel is nulled row-level in
    # dbt, one step before any aggregation, so this file carries no sentinel handling
    # at all — which is what makes R4.4's misplacement bug unexpressible here.
    description: "BUG(port): keeps SUPERFICIE = -1 in the denominator, exactly as OBIEE does — RULEBOOK R4.3 (bug_port), R4.6"
    type: sum_distinct
    sql_distinct_key: ${TABLE}.municipio_codigo ;;
    sql: ${TABLE}.municipio_superficie_km2_obiee ;;
    value_format_name: decimal_0
    hidden: yes
  }
  measure: superficie_comarca {
    # R4.1/R4.2 — `sum_distinct` keyed at the comarca level (comarca_codigo), never dimension_key.
    # R4.6 — reads the pre-guarded mart column. The sentinel is nulled row-level in
    # dbt, one step before any aggregation, so this file carries no sentinel handling
    # at all — which is what makes R4.4's misplacement bug unexpressible here.
    description: "Guarded denominator: area sentinels -1 and 0 are removed row-level in mart.dim_territorio — RULEBOOK R4.1, R4.2, R4.3 (null), R4.6"
    type: sum_distinct
    sql_distinct_key: ${TABLE}.comarca_codigo ;;
    sql: ${TABLE}.comarca_superficie_km2 ;;
    value_format_name: decimal_0
    hidden: yes
  }
  measure: superficie_comarca_raw {
    # R4.1/R4.2 — `sum_distinct` keyed at the comarca level (comarca_codigo), never dimension_key.
    # R4.6 — reads the pre-guarded mart column. The sentinel is nulled row-level in
    # dbt, one step before any aggregation, so this file carries no sentinel handling
    # at all — which is what makes R4.4's misplacement bug unexpressible here.
    description: "BUG(port): keeps SUPERFICIE = -1 in the denominator, exactly as OBIEE does — RULEBOOK R4.3 (bug_port), R4.6"
    type: sum_distinct
    sql_distinct_key: ${TABLE}.comarca_codigo ;;
    sql: ${TABLE}.comarca_superficie_km2_obiee ;;
    value_format_name: decimal_0
    hidden: yes
  }
  measure: superficie_provincia {
    # R4.1/R4.2 — `sum_distinct` keyed at the provincia level (provincia_codigo), never dimension_key.
    # R4.6 — reads the pre-guarded mart column. The sentinel is nulled row-level in
    # dbt, one step before any aggregation, so this file carries no sentinel handling
    # at all — which is what makes R4.4's misplacement bug unexpressible here.
    description: "Guarded denominator: area sentinels -1 and 0 are removed row-level in mart.dim_territorio — RULEBOOK R4.1, R4.2, R4.3 (null), R4.6"
    type: sum_distinct
    sql_distinct_key: ${TABLE}.provincia_codigo ;;
    sql: ${TABLE}.provincia_superficie_km2 ;;
    value_format_name: decimal_0
    hidden: yes
  }
  measure: superficie_provincia_raw {
    # R4.1/R4.2 — `sum_distinct` keyed at the provincia level (provincia_codigo), never dimension_key.
    # R4.6 — reads the pre-guarded mart column. The sentinel is nulled row-level in
    # dbt, one step before any aggregation, so this file carries no sentinel handling
    # at all — which is what makes R4.4's misplacement bug unexpressible here.
    description: "BUG(port): keeps SUPERFICIE = -1 in the denominator, exactly as OBIEE does — RULEBOOK R4.3 (bug_port), R4.6"
    type: sum_distinct
    sql_distinct_key: ${TABLE}.provincia_codigo ;;
    sql: ${TABLE}.provincia_superficie_km2_obiee ;;
    value_format_name: decimal_0
    hidden: yes
  }
  measure: superficie_aragon {
    # R4.1/R4.2 — `sum_distinct` keyed at the aragon level (provincia_superficie_km2), never dimension_key.
    # R4.6 — reads the pre-guarded mart column. The sentinel is nulled row-level in
    # dbt, one step before any aggregation, so this file carries no sentinel handling
    # at all — which is what makes R4.4's misplacement bug unexpressible here.
    # R4.0 — this is the logical column `Aragón superficie código`, whose physical
    # mapping is SUM(DISTINCT(PROVINCIA_SUPERFICIE)): an aggregate declared on a
    # dimension table, so it is a measure. R4.3 — OBIEE leaves it unscoped over the
    # whole 20-CCAA dimension, which is the one place the -1 sentinel leaks (47,720
    # vs 47,721 km²). The distinct key is the area column itself, not ccaa_codigo:
    # OBIEE's DISTINCT is on the value, and keying on ccaa_codigo counts the -1
    # once per CCAA that carries it (18x), giving 47,703 — neither ruling. Departs
    # from R4.2's table on purpose; see the generator docstring.
    description: "Guarded denominator: area sentinels -1 and 0 are removed row-level in mart.dim_territorio — RULEBOOK R4.1, R4.2, R4.3 (null), R4.6"
    type: sum_distinct
    sql_distinct_key: ${TABLE}.provincia_superficie_km2 ;;
    sql: ${TABLE}.provincia_superficie_km2 ;;
    value_format_name: decimal_0
    hidden: yes
  }
  measure: superficie_aragon_raw {
    # R4.1/R4.2 — `sum_distinct` keyed at the aragon level (provincia_superficie_km2_obiee), never dimension_key.
    # R4.6 — reads the pre-guarded mart column. The sentinel is nulled row-level in
    # dbt, one step before any aggregation, so this file carries no sentinel handling
    # at all — which is what makes R4.4's misplacement bug unexpressible here.
    # R4.0 — this is the logical column `Aragón superficie código`, whose physical
    # mapping is SUM(DISTINCT(PROVINCIA_SUPERFICIE)): an aggregate declared on a
    # dimension table, so it is a measure. R4.3 — OBIEE leaves it unscoped over the
    # whole 20-CCAA dimension, which is the one place the -1 sentinel leaks (47,720
    # vs 47,721 km²). The distinct key is the area column itself, not ccaa_codigo:
    # OBIEE's DISTINCT is on the value, and keying on ccaa_codigo counts the -1
    # once per CCAA that carries it (18x), giving 47,703 — neither ruling. Departs
    # from R4.2's table on purpose; see the generator docstring.
    description: "BUG(port): keeps SUPERFICIE = -1 in the denominator, exactly as OBIEE does — RULEBOOK R4.3 (bug_port), R4.6"
    type: sum_distinct
    sql_distinct_key: ${TABLE}.provincia_superficie_km2_obiee ;;
    sql: ${TABLE}.provincia_superficie_km2_obiee ;;
    value_format_name: decimal_0
    hidden: yes
  }
}
