view: +fct_censo_anual {
  # Generated by tools/gen_lookml.py from migration/ir/model.json.
  # Do not edit by hand; edit the generator or the IR.
  # Refinement of `fct_censo_anual` (views/base_views/fct_censo_anual.view.lkml): the measures - RULEBOOK R2, R3, R4.
  measure: personas {
    # R1.2 — the single additive measure. All 30 logical fact measures are
    # derived from it in LookML, never pre-aggregated in dbt: FILTER()
    # recomputes at the query's grain and pre-aggregating would fix it.
    label: "Personas"
    description: "OBIEE: TOTAL_POBLACION — RULEBOOK R1.2"
    type: sum
    sql: ${TABLE}.total_poblacion ;;
    value_format_name: decimal_0
    view_label: "Medidas"
    # R7.1 — drill set, not an inlined field list. The territory hierarchy is one tree
    # with a branch (Territorio Total → CCAA → { Provincia | Comarca } → Municipio) and
    # LookML allows one drill_fields chain per field, so administrativo as the default is
    # a design decision the client can reverse: point this at dim_territorio.drill_comarcal*.
    drill_fields: [dim_territorio.drill_administrativo*]
  }
  measure: personas_nacionalidad_extranjera {
    # `Personas nacionalidad extranjera` — R9.3 — reuses the R2 helper rather than duplicating the FILTER. This is the
    # one R2 condition that also ships as a user-facing measure.
    label: "Personas nacionalidad extranjera"
    description: "OBIEE: FILTER(Personas USING Nacionalidad país código <> '108') — RULEBOOK R2.1, R9.3"
    type: number
    sql: ${personas_pais_not_108} ;;
    value_format_name: decimal_0
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
  }
  measure: densidad_municipio {
    # `Densidad de población (municipio)` — R4.1 the denominator is an explicit sum_distinct measure
    # (LookML has no attribute that silently aggregates) · R3.2 SAFE_DIVIDE · R4.6 the
    # zero and -1 guards live in the mart column, so nothing is guarded out here.
    label: "Densidad de población (municipio)"
    description: "OBIEE: (Personas *1.0) /Municipio superficie código — RULEBOOK R4.1, R4.2, R4.3 (null), R4.6"
    type: number
    sql: SAFE_DIVIDE(${personas}, ${dim_territorio.superficie_municipio}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores"
  }
  measure: densidad_municipio_obiee {
    # `Densidad de población (municipio)` — R4.1 the denominator is an explicit sum_distinct measure
    # (LookML has no attribute that silently aggregates) · R3.2 SAFE_DIVIDE · R4.6 the
    # zero and -1 guards live in the mart column, so nothing is guarded out here.
    label: "Densidad de población (municipio) (paridad OBIEE)"
    description: "BUG(port): reproduces OBIEE dividing by SUPERFICIE = -1 where the area is unknown; the guarded twin is `densidad_municipio`. OBIEE: (Personas *1.0) /Municipio superficie código — RULEBOOK R4.3 (bug_port), R4.6"
    type: number
    sql: SAFE_DIVIDE(${personas}, ${dim_territorio.superficie_municipio_raw}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores (paridad OBIEE)"
  }
  measure: densidad_provincia {
    # `Densidad de población (provincia)` — R4.1 the denominator is an explicit sum_distinct measure
    # (LookML has no attribute that silently aggregates) · R3.2 SAFE_DIVIDE · R4.6 the
    # zero and -1 guards live in the mart column, so nothing is guarded out here.
    label: "Densidad de población (provincia)"
    description: "OBIEE: (Personas *1.0) /Provincia superficie código — RULEBOOK R4.1, R4.2, R4.3 (null), R4.6"
    type: number
    sql: SAFE_DIVIDE(${personas}, ${dim_territorio.superficie_provincia}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores"
  }
  measure: densidad_provincia_obiee {
    # `Densidad de población (provincia)` — R4.1 the denominator is an explicit sum_distinct measure
    # (LookML has no attribute that silently aggregates) · R3.2 SAFE_DIVIDE · R4.6 the
    # zero and -1 guards live in the mart column, so nothing is guarded out here.
    label: "Densidad de población (provincia) (paridad OBIEE)"
    description: "BUG(port): reproduces OBIEE dividing by SUPERFICIE = -1 where the area is unknown; the guarded twin is `densidad_provincia`. OBIEE: (Personas *1.0) /Provincia superficie código — RULEBOOK R4.3 (bug_port), R4.6"
    type: number
    sql: SAFE_DIVIDE(${personas}, ${dim_territorio.superficie_provincia_raw}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores (paridad OBIEE)"
  }
  measure: densidad_comarca {
    # `Densidad de población (comarca)` — R4.1 the denominator is an explicit sum_distinct measure
    # (LookML has no attribute that silently aggregates) · R3.2 SAFE_DIVIDE · R4.6 the
    # zero and -1 guards live in the mart column, so nothing is guarded out here.
    label: "Densidad de población (comarca)"
    description: "OBIEE: (Personas *1.0) /Comarca superficie código — RULEBOOK R4.1, R4.2, R4.3 (null), R4.6"
    type: number
    sql: SAFE_DIVIDE(${personas}, ${dim_territorio.superficie_comarca}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores"
  }
  measure: densidad_comarca_obiee {
    # `Densidad de población (comarca)` — R4.1 the denominator is an explicit sum_distinct measure
    # (LookML has no attribute that silently aggregates) · R3.2 SAFE_DIVIDE · R4.6 the
    # zero and -1 guards live in the mart column, so nothing is guarded out here.
    label: "Densidad de población (comarca) (paridad OBIEE)"
    description: "BUG(port): reproduces OBIEE dividing by SUPERFICIE = -1 where the area is unknown; the guarded twin is `densidad_comarca`. OBIEE: (Personas *1.0) /Comarca superficie código — RULEBOOK R4.3 (bug_port), R4.6"
    type: number
    sql: SAFE_DIVIDE(${personas}, ${dim_territorio.superficie_comarca_raw}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores (paridad OBIEE)"
  }
  measure: densidad_aragon {
    # `Densidad de población (Aragón)` — R4.1 the denominator is an explicit sum_distinct measure
    # (LookML has no attribute that silently aggregates) · R3.2 SAFE_DIVIDE · R4.6 the
    # zero and -1 guards live in the mart column, so nothing is guarded out here.
    label: "Densidad de población (Aragón)"
    description: "OBIEE: (Personas *1.0) /Aragón superficie código — RULEBOOK R4.1, R4.2, R4.3 (null), R4.6"
    type: number
    sql: SAFE_DIVIDE(${personas}, ${dim_territorio.superficie_aragon}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores"
  }
  measure: densidad_aragon_obiee {
    # `Densidad de población (Aragón)` — R4.1 the denominator is an explicit sum_distinct measure
    # (LookML has no attribute that silently aggregates) · R3.2 SAFE_DIVIDE · R4.6 the
    # zero and -1 guards live in the mart column, so nothing is guarded out here.
    label: "Densidad de población (Aragón) (paridad OBIEE)"
    description: "BUG(port): reproduces OBIEE dividing by SUPERFICIE = -1 where the area is unknown; the guarded twin is `densidad_aragon`. OBIEE: (Personas *1.0) /Aragón superficie código — RULEBOOK R4.3 (bug_port), R4.6"
    type: number
    sql: SAFE_DIVIDE(${personas}, ${dim_territorio.superficie_aragon_raw}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores (paridad OBIEE)"
  }
  measure: pct_poblacion_0_19_annos {
    # `% de población de 0 a 19 años` — R3.1 number over R2 helpers · R3.2 SAFE_DIVIDE (DEV-DIV: Looker returns NULL
    # where OBIEE errored) · R3.3 COALESCE on the numerator only · R3.4 100.0d → 100.0
    label: "% de población de 0 a 19 años"
    description: "OBIEE: IFNULL( FILTER(Personas USING Edad (año a año) BETWEEN 0 AND 19), 0) * 100.0d / Personas — RULEBOOK R3.1, R3.2, R3.3, R3.4"
    type: number
    sql: SAFE_DIVIDE(COALESCE(${personas_edad_0_19}, 0) * 100.0, ${personas}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores"
  }
  measure: pct_poblacion_20_64_annos {
    # `% de población de 20 a 64 años` — R3.1 number over R2 helpers · R3.2 SAFE_DIVIDE (DEV-DIV: Looker returns NULL
    # where OBIEE errored) · R3.3 COALESCE on the numerator only · R3.4 100.0d → 100.0
    label: "% de población de 20 a 64 años"
    description: "OBIEE: IFNULL( FILTER(Personas USING Edad (año a año) BETWEEN 20 AND 64), 0) * 100.0d / Personas — RULEBOOK R3.1, R3.2, R3.3, R3.4"
    type: number
    sql: SAFE_DIVIDE(COALESCE(${personas_edad_20_64}, 0) * 100.0, ${personas}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores"
  }
  measure: pct_poblacion_65_mas_annos {
    # `% de población de 65 y más años` — R3.1 number over R2 helpers · R3.2 SAFE_DIVIDE (DEV-DIV: Looker returns NULL
    # where OBIEE errored) · R3.3 COALESCE on the numerator only · R3.4 100.0d → 100.0
    label: "% de población de 65 y más años"
    description: "OBIEE: IFNULL( FILTER(Personas USING Edad (año a año) >= 65), 0) * 100.0d / Personas — RULEBOOK R3.1, R3.2, R3.3, R3.4"
    type: number
    sql: SAFE_DIVIDE(COALESCE(${personas_edad_gte_65}, 0) * 100.0, ${personas}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores"
  }
  measure: pct_poblacion_80_mas_annos {
    # `% de población de 80 y más años` — R3.1 number over R2 helpers · R3.2 SAFE_DIVIDE (DEV-DIV: Looker returns NULL
    # where OBIEE errored) · R3.3 COALESCE on the numerator only · R3.4 100.0d → 100.0
    label: "% de población de 80 y más años"
    description: "OBIEE: IFNULL( FILTER(Personas USING Edad (año a año) > 79), 0) * 100.0d / Personas — RULEBOOK R3.1, R3.2, R3.3, R3.4"
    type: number
    sql: SAFE_DIVIDE(COALESCE(${personas_edad_gt_79}, 0) * 100.0, ${personas}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores"
  }
  measure: pct_poblacion_menor_1 {
    # `% de población menor de 1` — R3.1 number over R2 helpers · R3.2 SAFE_DIVIDE (DEV-DIV: Looker returns NULL
    # where OBIEE errored) · R3.3 COALESCE on the numerator only · R3.4 100.0d → 100.0
    label: "% de población menor de 1"
    description: "OBIEE: IFNULL( FILTER(Personas USING Edad (año a año) < 1), 0) * 100.0d / Personas — RULEBOOK R3.1, R3.2, R3.3, R3.4"
    type: number
    sql: SAFE_DIVIDE(COALESCE(${personas_edad_lt_1}, 0) * 100.0, ${personas}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores"
  }
  measure: pct_poblacion_menor_15 {
    # `% de población menor de 15` — R3.1 number over R2 helpers · R3.2 SAFE_DIVIDE (DEV-DIV: Looker returns NULL
    # where OBIEE errored) · R3.3 COALESCE on the numerator only · R3.4 100.0d → 100.0
    label: "% de población menor de 15"
    description: "OBIEE: IFNULL( FILTER(Personas USING Edad (año a año) < 15), 0) * 100.0d / Personas — RULEBOOK R3.1, R3.2, R3.3, R3.4"
    type: number
    sql: SAFE_DIVIDE(COALESCE(${personas_edad_lt_15}, 0) * 100.0, ${personas}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores"
  }
  measure: pct_poblacion_menor_25 {
    # `% de población menor de 25` — R3.1 number over R2 helpers · R3.2 SAFE_DIVIDE (DEV-DIV: Looker returns NULL
    # where OBIEE errored) · R3.3 COALESCE on the numerator only · R3.4 100.0d → 100.0
    label: "% de población menor de 25"
    description: "OBIEE: IFNULL( FILTER(Personas USING Edad (año a año) < 25), 0) * 100.0d / Personas — RULEBOOK R3.1, R3.2, R3.3, R3.4"
    type: number
    sql: SAFE_DIVIDE(COALESCE(${personas_edad_lt_25}, 0) * 100.0, ${personas}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores"
  }
  measure: pct_poblacion_menor_35 {
    # `% de población menor de 35` — R3.1 number over R2 helpers · R3.2 SAFE_DIVIDE (DEV-DIV: Looker returns NULL
    # where OBIEE errored) · R3.3 COALESCE on the numerator only · R3.4 100.0d → 100.0
    label: "% de población menor de 35"
    description: "OBIEE: IFNULL( FILTER(Personas USING Edad (año a año) < 35), 0) * 100.0d / Personas — RULEBOOK R3.1, R3.2, R3.3, R3.4"
    type: number
    sql: SAFE_DIVIDE(COALESCE(${personas_edad_lt_35}, 0) * 100.0, ${personas}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores"
  }
  measure: pct_poblacion_menor_45 {
    # `% de población menor de 45` — R3.1 number over R2 helpers · R3.2 SAFE_DIVIDE (DEV-DIV: Looker returns NULL
    # where OBIEE errored) · R3.3 COALESCE on the numerator only · R3.4 100.0d → 100.0
    label: "% de población menor de 45"
    description: "OBIEE: IFNULL( FILTER(Personas USING Edad (año a año) < 45), 0) * 100.0d / Personas — RULEBOOK R3.1, R3.2, R3.3, R3.4"
    type: number
    sql: SAFE_DIVIDE(COALESCE(${personas_edad_lt_45}, 0) * 100.0, ${personas}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores"
  }
  measure: indice_envejecimiento {
    # `Índice de envejecimiento` — R3.1 number over R2 helpers · R3.2 SAFE_DIVIDE (DEV-DIV: Looker returns NULL
    # where OBIEE errored) · R3.3 COALESCE on the numerator only · R3.4 100.0d → 100.0
    label: "Índice de envejecimiento"
    description: "OBIEE: IFNULL( FILTER(Personas USING Edad (año a año) > 64), 0) * 100.0d / FILTER(Personas USING Edad (año a año) BETWEEN 0 AND 19) — RULEBOOK R3.1, R3.2, R3.3, R3.4"
    type: number
    sql: SAFE_DIVIDE(COALESCE(${personas_edad_gt_64}, 0) * 100.0, ${personas_edad_0_19}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores"
  }
  measure: indice_juventud {
    # `Índice de juventud` — R3.1 number over R2 helpers · R3.2 SAFE_DIVIDE (DEV-DIV: Looker returns NULL
    # where OBIEE errored) · R3.3 COALESCE on the numerator only · R3.4 100.0d → 100.0
    label: "Índice de juventud"
    description: "OBIEE: IFNULL( FILTER(Personas USING Edad (año a año) BETWEEN 0 AND 14), 0) * 100.0d / FILTER(Personas USING Edad (año a año) > 64) — RULEBOOK R3.1, R3.2, R3.3, R3.4"
    type: number
    sql: SAFE_DIVIDE(COALESCE(${personas_edad_0_14}, 0) * 100.0, ${personas_edad_gt_64}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores"
  }
  measure: indice_vejez {
    # `Índice de vejez` — R3.1 number over R2 helpers · R3.2 SAFE_DIVIDE (DEV-DIV: Looker returns NULL
    # where OBIEE errored) · R3.3 COALESCE on the numerator only · R3.4 100.0d → 100.0
    label: "Índice de vejez"
    description: "OBIEE: IFNULL( FILTER(Personas USING Edad (año a año) >64), 0) * 100.0d / FILTER(Personas USING Edad (año a año) BETWEEN 0 AND 14) — RULEBOOK R3.1, R3.2, R3.3, R3.4"
    type: number
    sql: SAFE_DIVIDE(COALESCE(${personas_edad_gt_64}, 0) * 100.0, ${personas_edad_0_14}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores"
  }
  measure: indice_sobreenvejecimiento {
    # `Índice de sobreenvejecimiento` — R3.1 number over R2 helpers · R3.2 SAFE_DIVIDE (DEV-DIV: Looker returns NULL
    # where OBIEE errored) · R3.3 COALESCE on the numerator only · R3.4 100.0d → 100.0
    label: "Índice de sobreenvejecimiento"
    description: "OBIEE: IFNULL( FILTER(Personas USING Edad (año a año) >84), 0) * 100.0d / FILTER(Personas USING Edad (año a año) >64) — RULEBOOK R3.1, R3.2, R3.3, R3.4"
    type: number
    sql: SAFE_DIVIDE(COALESCE(${personas_edad_gt_84}, 0) * 100.0, ${personas_edad_gt_64}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores"
  }
  measure: indice_ancianidad {
    # `Índice de ancianidad` — R3.1 number over R2 helpers · R3.2 SAFE_DIVIDE (DEV-DIV: Looker returns NULL
    # where OBIEE errored) · R3.3 COALESCE on the numerator only · R3.4 100.0d → 100.0
    label: "Índice de ancianidad"
    description: "OBIEE: IFNULL( FILTER(Personas USING Edad (año a año) BETWEEN 75 AND 84), 0) * 100.0d / FILTER(Personas USING Edad (año a año) >64) — RULEBOOK R3.1, R3.2, R3.3, R3.4"
    type: number
    sql: SAFE_DIVIDE(COALESCE(${personas_edad_75_84}, 0) * 100.0, ${personas_edad_gt_64}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores"
  }
  measure: tasa_global_dependencia {
    # `Tasa global de dependencia` — R3.1 number over R2 helpers · R3.2 SAFE_DIVIDE (DEV-DIV: Looker returns NULL
    # where OBIEE errored) · R3.3 COALESCE on the numerator only · R3.4 100.0d → 100.0
    label: "Tasa global de dependencia"
    description: "OBIEE: ( IFNULL( FILTER(Personas USING Edad (año a año) > 64), 0) + IFNULL( FILTER(Personas USING Edad (año a año) BETWEEN 0 AND 14), 0)) * 100.0d / FILTER(Personas USING Edad (año a año) BETWEEN 15 AND 64) — RULEBOOK R3.1, R3.2, R3.3, R3.4"
    type: number
    sql: SAFE_DIVIDE((COALESCE(${personas_edad_gt_64}, 0) + COALESCE(${personas_edad_0_14}, 0)) * 100.0, ${personas_edad_15_64}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores"
  }
  measure: tasa_global_dependencia_ancianos {
    # `Tasa global de dependencia ancianos` — R3.1 number over R2 helpers · R3.2 SAFE_DIVIDE (DEV-DIV: Looker returns NULL
    # where OBIEE errored) · R3.3 COALESCE on the numerator only · R3.4 100.0d → 100.0
    label: "Tasa global de dependencia ancianos"
    description: "OBIEE: IFNULL( FILTER(Personas USING Edad (año a año) > 64), 0) * 100.0d / FILTER(Personas USING Edad (año a año) BETWEEN 15 AND 64) — RULEBOOK R3.1, R3.2, R3.3, R3.4"
    type: number
    sql: SAFE_DIVIDE(COALESCE(${personas_edad_gt_64}, 0) * 100.0, ${personas_edad_15_64}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores"
  }
  measure: tasa_global_dependencia_jovenes {
    # `Tasa global de dependencia jóvenes` — R3.1 number over R2 helpers · R3.2 SAFE_DIVIDE (DEV-DIV: Looker returns NULL
    # where OBIEE errored) · R3.3 COALESCE on the numerator only · R3.4 100.0d → 100.0
    label: "Tasa global de dependencia jóvenes"
    description: "OBIEE: IFNULL( FILTER(Personas USING Edad (año a año) BETWEEN 0 AND 14), 0) * 100.0d / FILTER(Personas USING Edad (año a año) BETWEEN 15 AND 64) — RULEBOOK R3.1, R3.2, R3.3, R3.4"
    type: number
    sql: SAFE_DIVIDE(COALESCE(${personas_edad_0_14}, 0) * 100.0, ${personas_edad_15_64}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores"
  }
  measure: indice_estructura_poblacion_activa_total {
    # `Índice estructura de población activa total` — R3.1 number over R2 helpers · R3.2 SAFE_DIVIDE (DEV-DIV: Looker returns NULL
    # where OBIEE errored) · R3.3 COALESCE on the numerator only · R3.4 100.0d → 100.0
    label: "Índice estructura de población activa total"
    description: "OBIEE: IFNULL( FILTER(Personas USING Edad (año a año) BETWEEN 16 AND 39), 0) * 100.0d / FILTER(Personas USING Edad (año a año) BETWEEN 40 AND 64) — RULEBOOK R3.1, R3.2, R3.3, R3.4"
    type: number
    sql: SAFE_DIVIDE(COALESCE(${personas_edad_16_39}, 0) * 100.0, ${personas_edad_40_64}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores"
  }
  measure: indice_reemplazamiento_edad_activa_total {
    # `Índice reemplazamiento edad activa total` — R3.1 number over R2 helpers · R3.2 SAFE_DIVIDE (DEV-DIV: Looker returns NULL
    # where OBIEE errored) · R3.3 COALESCE on the numerator only · R3.4 100.0d → 100.0
    label: "Índice reemplazamiento edad activa total"
    description: "OBIEE: IFNULL( FILTER(Personas USING Edad (año a año) BETWEEN 16 AND 19), 0) * 100.0d / FILTER(Personas USING Edad (año a año) BETWEEN 60 AND 64) — RULEBOOK R3.1, R3.2, R3.3, R3.4"
    type: number
    sql: SAFE_DIVIDE(COALESCE(${personas_edad_16_19}, 0) * 100.0, ${personas_edad_60_64}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores"
  }
  measure: tasa_masculinidad {
    # `Tasa de masculinidad` — R3.1 number over R2 helpers · R3.2 SAFE_DIVIDE (DEV-DIV: Looker returns NULL
    # where OBIEE errored) · R3.3 COALESCE on the numerator only · R3.4 100.0d → 100.0
    label: "Tasa de masculinidad"
    description: "OBIEE: IFNULL( FILTER(Personas USING Sexo (código) = '1'), 0) * 100.0d / FILTER(Personas USING Sexo (código) = '6') — RULEBOOK R3.1, R3.2, R3.3, R3.4"
    type: number
    sql: SAFE_DIVIDE(COALESCE(${personas_sexo_1}, 0) * 100.0, ${personas_sexo_6}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores"
  }
  measure: tasa_feminidad {
    # `Tasa de feminidad` — R3.1 number over R2 helpers · R3.2 SAFE_DIVIDE (DEV-DIV: Looker returns NULL
    # where OBIEE errored) · R3.3 COALESCE on the numerator only · R3.4 100.0d → 100.0
    label: "Tasa de feminidad"
    description: "OBIEE: IFNULL( FILTER(Personas USING Sexo (código) = '6'), 0) * 100.0d / FILTER(Personas USING Sexo (código) = '1') — RULEBOOK R3.1, R3.2, R3.3, R3.4"
    type: number
    sql: SAFE_DIVIDE(COALESCE(${personas_sexo_6}, 0) * 100.0, ${personas_sexo_1}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores"
  }
  measure: indice_maternidad {
    # `Índice de maternidad` — R3.1 number over R2 helpers · R3.2 SAFE_DIVIDE (DEV-DIV: Looker returns NULL
    # where OBIEE errored) · R3.3 COALESCE on the numerator only · R3.4 100.0d → 100.0
    label: "Índice de maternidad"
    description: "OBIEE: IFNULL( FILTER(Personas USING Edad (año a año) BETWEEN 0 AND 4), 0) * 100.0d / FILTER(Personas USING Sexo (código) = '6' AND Edad (año a año) BETWEEN 15 AND 49) — RULEBOOK R3.1, R3.2, R3.3, R3.4"
    type: number
    sql: SAFE_DIVIDE(COALESCE(${personas_edad_0_4}, 0) * 100.0, ${personas_sexo_6_edad_15_49}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores"
  }
  measure: indice_potencialidad {
    # `Índice de potencialidad` — R3.1 number over R2 helpers · R3.2 SAFE_DIVIDE (DEV-DIV: Looker returns NULL
    # where OBIEE errored) · R3.3 COALESCE on the numerator only · R3.4 100.0d → 100.0
    label: "Índice de potencialidad"
    description: "OBIEE: IFNULL( FILTER(Personas USING Sexo (código) = '6' AND Edad (año a año) BETWEEN 20 AND 34), 0) * 100.0d / FILTER(Personas USING Sexo (código) = '6' AND Edad (año a año) BETWEEN 35 AND 49) — RULEBOOK R3.1, R3.2, R3.3, R3.4"
    type: number
    sql: SAFE_DIVIDE(COALESCE(${personas_sexo_6_edad_20_34}, 0) * 100.0, ${personas_sexo_6_edad_35_49}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores"
  }
  measure: porcentaje_poblacion_extranjera {
    # `Porcentaje población extranjera` — R3.1 number over R2 helpers · R3.2 SAFE_DIVIDE (DEV-DIV: Looker returns NULL
    # where OBIEE errored) · R3.3 COALESCE on the numerator only · R3.4 100.0d → 100.0
    label: "Porcentaje población extranjera"
    description: "OBIEE: IFNULL( FILTER(Personas USING Nacionalidad país código <> '108'), 0) * 100.0d / Personas — RULEBOOK R3.1, R3.2, R3.3, R3.4"
    type: number
    sql: SAFE_DIVIDE(COALESCE(${personas_pais_not_108}, 0) * 100.0, ${personas}) ;;
    value_format_name: decimal_2
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
    group_label: "Indicadores"
  }
  measure: poblacion_hombres {
    # `Población (Hombres)` — a column of `Análisis - Población por Municipio.xml`, not of the RPD.
    # R9.3 — reuses the R2 helper `personas_sexo_1` rather than defining a second FILTER.
    # The analysis filters the label (Sexo = 'Hombre'), the helper filters the code (Sexo (código) =
    # '1'); DIM_SEXO_DATA_TABLE.csv has exactly three rows — 1 Hombre, 6 Mujer,
    # 0 Desconocido/a — so the two predicates select identical rows. An extract that
    # changed those codes would invalidate this reuse.
    # Visible because a `hidden: yes` helper (R2.1) cannot be named by a dashboard
    # element; same shape as `Personas nacionalidad extranjera`.
    label: "Población (Hombres)"
    description: "OBIEE: FILTER(Personas USING Sexo = 'Hombre') — column of `Población por Municipio`, resolved to the code-keyed helper personas_sexo_1 on the verified mapping 1 = Hombre — RULEBOOK R2.1, R9.3"
    type: number
    sql: ${personas_sexo_1} ;;
    value_format_name: decimal_0
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
  }
  measure: poblacion_mujeres {
    # `Población (Mujeres)` — a column of `Análisis - Población por Municipio.xml`, not of the RPD.
    # R9.3 — reuses the R2 helper `personas_sexo_6` rather than defining a second FILTER.
    # The analysis filters the label (Sexo = 'Mujer'), the helper filters the code (Sexo (código) =
    # '6'); DIM_SEXO_DATA_TABLE.csv has exactly three rows — 1 Hombre, 6 Mujer,
    # 0 Desconocido/a — so the two predicates select identical rows. An extract that
    # changed those codes would invalidate this reuse.
    # Visible because a `hidden: yes` helper (R2.1) cannot be named by a dashboard
    # element; same shape as `Personas nacionalidad extranjera`.
    label: "Población (Mujeres)"
    description: "OBIEE: FILTER(Personas USING Sexo = 'Mujer') — column of `Población por Municipio`, resolved to the code-keyed helper personas_sexo_6 on the verified mapping 6 = Mujer — RULEBOOK R2.1, R9.3"
    type: number
    sql: ${personas_sexo_6} ;;
    value_format_name: decimal_0
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
  }
  measure: sexo_diferencia {
    # `Sexo_diferencia` — a column of `Análisis - Población por Municipio Formateada.xml`,
    # not of the RPD (R9.7). Subtraction of the two R9.3 twins, not a third FILTER.
    # In OBIEE it is what the analysis's conditional formatting reads: positive
    # means the municipality has more men than women.
    label: "Sexo_diferencia"
    description: "OBIEE: FILTER(Personas USING Sexo = 'Hombre') - FILTER(Personas USING Sexo = 'Mujer') — column of `Población por Municipio Formateada` — RULEBOOK R9.3, R9.7"
    type: number
    sql: ${poblacion_hombres} - ${poblacion_mujeres} ;;
    value_format_name: decimal_0
    view_label: "Medidas"
    drill_fields: [dim_territorio.drill_administrativo*]
  }
  measure: personas_edad_0_19 {
    # R2 helper — used by `% de población de 0 a 19 años`, `Índice de envejecimiento`.
    # R2.6 naming; R2.4 keeps this separate from any semantically equal condition
    # written differently in the RPD, so every measure traces to one ExprTextDesc.
    description: "FILTER(Personas USING Edad (año a año) BETWEEN 0 AND 19) — RULEBOOK R2.1, R2.2, R2.6"
    type: sum
    sql: ${TABLE}.total_poblacion ;;
    filters: [dim_edad.edad_anno_anno: "0 to 19"]
    value_format_name: decimal_0
    view_label: "Medidas"
    hidden: yes
  }
  measure: personas_edad_20_64 {
    # R2 helper — used by `% de población de 20 a 64 años`.
    # R2.6 naming; R2.4 keeps this separate from any semantically equal condition
    # written differently in the RPD, so every measure traces to one ExprTextDesc.
    description: "FILTER(Personas USING Edad (año a año) BETWEEN 20 AND 64) — RULEBOOK R2.1, R2.2, R2.6"
    type: sum
    sql: ${TABLE}.total_poblacion ;;
    filters: [dim_edad.edad_anno_anno: "20 to 64"]
    value_format_name: decimal_0
    view_label: "Medidas"
    hidden: yes
  }
  measure: personas_edad_gte_65 {
    # R2 helper — used by `% de población de 65 y más años`.
    # R2.6 naming; R2.4 keeps this separate from any semantically equal condition
    # written differently in the RPD, so every measure traces to one ExprTextDesc.
    description: "FILTER(Personas USING Edad (año a año) >= 65) — RULEBOOK R2.1, R2.2, R2.6"
    type: sum
    sql: ${TABLE}.total_poblacion ;;
    filters: [dim_edad.edad_anno_anno: ">=65"]
    value_format_name: decimal_0
    view_label: "Medidas"
    hidden: yes
  }
  measure: personas_edad_gt_79 {
    # R2 helper — used by `% de población de 80 y más años`.
    # R2.6 naming; R2.4 keeps this separate from any semantically equal condition
    # written differently in the RPD, so every measure traces to one ExprTextDesc.
    description: "FILTER(Personas USING Edad (año a año) > 79) — RULEBOOK R2.1, R2.2, R2.6"
    type: sum
    sql: ${TABLE}.total_poblacion ;;
    filters: [dim_edad.edad_anno_anno: ">79"]
    value_format_name: decimal_0
    view_label: "Medidas"
    hidden: yes
  }
  measure: personas_edad_lt_1 {
    # R2 helper — used by `% de población menor de 1`.
    # R2.6 naming; R2.4 keeps this separate from any semantically equal condition
    # written differently in the RPD, so every measure traces to one ExprTextDesc.
    description: "FILTER(Personas USING Edad (año a año) < 1) — RULEBOOK R2.1, R2.2, R2.6"
    type: sum
    sql: ${TABLE}.total_poblacion ;;
    filters: [dim_edad.edad_anno_anno: "<1"]
    value_format_name: decimal_0
    view_label: "Medidas"
    hidden: yes
  }
  measure: personas_edad_lt_15 {
    # R2 helper — used by `% de población menor de 15`.
    # R2.6 naming; R2.4 keeps this separate from any semantically equal condition
    # written differently in the RPD, so every measure traces to one ExprTextDesc.
    description: "FILTER(Personas USING Edad (año a año) < 15) — RULEBOOK R2.1, R2.2, R2.6"
    type: sum
    sql: ${TABLE}.total_poblacion ;;
    filters: [dim_edad.edad_anno_anno: "<15"]
    value_format_name: decimal_0
    view_label: "Medidas"
    hidden: yes
  }
  measure: personas_edad_lt_25 {
    # R2 helper — used by `% de población menor de 25`.
    # R2.6 naming; R2.4 keeps this separate from any semantically equal condition
    # written differently in the RPD, so every measure traces to one ExprTextDesc.
    description: "FILTER(Personas USING Edad (año a año) < 25) — RULEBOOK R2.1, R2.2, R2.6"
    type: sum
    sql: ${TABLE}.total_poblacion ;;
    filters: [dim_edad.edad_anno_anno: "<25"]
    value_format_name: decimal_0
    view_label: "Medidas"
    hidden: yes
  }
  measure: personas_edad_lt_35 {
    # R2 helper — used by `% de población menor de 35`.
    # R2.6 naming; R2.4 keeps this separate from any semantically equal condition
    # written differently in the RPD, so every measure traces to one ExprTextDesc.
    description: "FILTER(Personas USING Edad (año a año) < 35) — RULEBOOK R2.1, R2.2, R2.6"
    type: sum
    sql: ${TABLE}.total_poblacion ;;
    filters: [dim_edad.edad_anno_anno: "<35"]
    value_format_name: decimal_0
    view_label: "Medidas"
    hidden: yes
  }
  measure: personas_edad_lt_45 {
    # R2 helper — used by `% de población menor de 45`.
    # R2.6 naming; R2.4 keeps this separate from any semantically equal condition
    # written differently in the RPD, so every measure traces to one ExprTextDesc.
    description: "FILTER(Personas USING Edad (año a año) < 45) — RULEBOOK R2.1, R2.2, R2.6"
    type: sum
    sql: ${TABLE}.total_poblacion ;;
    filters: [dim_edad.edad_anno_anno: "<45"]
    value_format_name: decimal_0
    view_label: "Medidas"
    hidden: yes
  }
  measure: personas_edad_gt_64 {
    # R2 helper — used by `Índice de envejecimiento`, `Índice de juventud`, `Índice de vejez`, `Índice de sobreenvejecimiento`, `Índice de ancianidad`, `Tasa global de dependencia`, `Tasa global de dependencia ancianos`.
    # R2.6 naming; R2.4 keeps this separate from any semantically equal condition
    # written differently in the RPD, so every measure traces to one ExprTextDesc.
    description: "FILTER(Personas USING Edad (año a año) > 64) — RULEBOOK R2.1, R2.2, R2.6"
    type: sum
    sql: ${TABLE}.total_poblacion ;;
    filters: [dim_edad.edad_anno_anno: ">64"]
    value_format_name: decimal_0
    view_label: "Medidas"
    hidden: yes
  }
  measure: personas_edad_0_14 {
    # R2 helper — used by `Índice de juventud`, `Índice de vejez`, `Tasa global de dependencia`, `Tasa global de dependencia jóvenes`.
    # R2.6 naming; R2.4 keeps this separate from any semantically equal condition
    # written differently in the RPD, so every measure traces to one ExprTextDesc.
    description: "FILTER(Personas USING Edad (año a año) BETWEEN 0 AND 14) — RULEBOOK R2.1, R2.2, R2.6"
    type: sum
    sql: ${TABLE}.total_poblacion ;;
    filters: [dim_edad.edad_anno_anno: "0 to 14"]
    value_format_name: decimal_0
    view_label: "Medidas"
    hidden: yes
  }
  measure: personas_edad_gt_84 {
    # R2 helper — used by `Índice de sobreenvejecimiento`.
    # R2.6 naming; R2.4 keeps this separate from any semantically equal condition
    # written differently in the RPD, so every measure traces to one ExprTextDesc.
    description: "FILTER(Personas USING Edad (año a año) > 84) — RULEBOOK R2.1, R2.2, R2.6"
    type: sum
    sql: ${TABLE}.total_poblacion ;;
    filters: [dim_edad.edad_anno_anno: ">84"]
    value_format_name: decimal_0
    view_label: "Medidas"
    hidden: yes
  }
  measure: personas_edad_75_84 {
    # R2 helper — used by `Índice de ancianidad`.
    # R2.6 naming; R2.4 keeps this separate from any semantically equal condition
    # written differently in the RPD, so every measure traces to one ExprTextDesc.
    description: "FILTER(Personas USING Edad (año a año) BETWEEN 75 AND 84) — RULEBOOK R2.1, R2.2, R2.6"
    type: sum
    sql: ${TABLE}.total_poblacion ;;
    filters: [dim_edad.edad_anno_anno: "75 to 84"]
    value_format_name: decimal_0
    view_label: "Medidas"
    hidden: yes
  }
  measure: personas_edad_15_64 {
    # R2 helper — used by `Tasa global de dependencia`, `Tasa global de dependencia ancianos`, `Tasa global de dependencia jóvenes`.
    # R2.6 naming; R2.4 keeps this separate from any semantically equal condition
    # written differently in the RPD, so every measure traces to one ExprTextDesc.
    description: "FILTER(Personas USING Edad (año a año) BETWEEN 15 AND 64) — RULEBOOK R2.1, R2.2, R2.6"
    type: sum
    sql: ${TABLE}.total_poblacion ;;
    filters: [dim_edad.edad_anno_anno: "15 to 64"]
    value_format_name: decimal_0
    view_label: "Medidas"
    hidden: yes
  }
  measure: personas_edad_16_39 {
    # R2 helper — used by `Índice estructura de población activa total`.
    # R2.6 naming; R2.4 keeps this separate from any semantically equal condition
    # written differently in the RPD, so every measure traces to one ExprTextDesc.
    description: "FILTER(Personas USING Edad (año a año) BETWEEN 16 AND 39) — RULEBOOK R2.1, R2.2, R2.6"
    type: sum
    sql: ${TABLE}.total_poblacion ;;
    filters: [dim_edad.edad_anno_anno: "16 to 39"]
    value_format_name: decimal_0
    view_label: "Medidas"
    hidden: yes
  }
  measure: personas_edad_40_64 {
    # R2 helper — used by `Índice estructura de población activa total`.
    # R2.6 naming; R2.4 keeps this separate from any semantically equal condition
    # written differently in the RPD, so every measure traces to one ExprTextDesc.
    description: "FILTER(Personas USING Edad (año a año) BETWEEN 40 AND 64) — RULEBOOK R2.1, R2.2, R2.6"
    type: sum
    sql: ${TABLE}.total_poblacion ;;
    filters: [dim_edad.edad_anno_anno: "40 to 64"]
    value_format_name: decimal_0
    view_label: "Medidas"
    hidden: yes
  }
  measure: personas_edad_16_19 {
    # R2 helper — used by `Índice reemplazamiento edad activa total`.
    # R2.6 naming; R2.4 keeps this separate from any semantically equal condition
    # written differently in the RPD, so every measure traces to one ExprTextDesc.
    description: "FILTER(Personas USING Edad (año a año) BETWEEN 16 AND 19) — RULEBOOK R2.1, R2.2, R2.6"
    type: sum
    sql: ${TABLE}.total_poblacion ;;
    filters: [dim_edad.edad_anno_anno: "16 to 19"]
    value_format_name: decimal_0
    view_label: "Medidas"
    hidden: yes
  }
  measure: personas_edad_60_64 {
    # R2 helper — used by `Índice reemplazamiento edad activa total`.
    # R2.6 naming; R2.4 keeps this separate from any semantically equal condition
    # written differently in the RPD, so every measure traces to one ExprTextDesc.
    description: "FILTER(Personas USING Edad (año a año) BETWEEN 60 AND 64) — RULEBOOK R2.1, R2.2, R2.6"
    type: sum
    sql: ${TABLE}.total_poblacion ;;
    filters: [dim_edad.edad_anno_anno: "60 to 64"]
    value_format_name: decimal_0
    view_label: "Medidas"
    hidden: yes
  }
  measure: personas_sexo_1 {
    # R2 helper — used by `Tasa de masculinidad`, `Tasa de feminidad`.
    # R2.6 naming; R2.4 keeps this separate from any semantically equal condition
    # written differently in the RPD, so every measure traces to one ExprTextDesc.
    description: "FILTER(Personas USING Sexo (código) = '1') — RULEBOOK R2.1, R2.2, R2.6"
    type: sum
    sql: ${TABLE}.total_poblacion ;;
    filters: [dim_sexo.sexo_codigo: "1"]
    value_format_name: decimal_0
    view_label: "Medidas"
    hidden: yes
  }
  measure: personas_sexo_6 {
    # R2 helper — used by `Tasa de masculinidad`, `Tasa de feminidad`.
    # R2.6 naming; R2.4 keeps this separate from any semantically equal condition
    # written differently in the RPD, so every measure traces to one ExprTextDesc.
    description: "FILTER(Personas USING Sexo (código) = '6') — RULEBOOK R2.1, R2.2, R2.6"
    type: sum
    sql: ${TABLE}.total_poblacion ;;
    filters: [dim_sexo.sexo_codigo: "6"]
    value_format_name: decimal_0
    view_label: "Medidas"
    hidden: yes
  }
  measure: personas_edad_0_4 {
    # R2 helper — used by `Índice de maternidad`.
    # R2.6 naming; R2.4 keeps this separate from any semantically equal condition
    # written differently in the RPD, so every measure traces to one ExprTextDesc.
    description: "FILTER(Personas USING Edad (año a año) BETWEEN 0 AND 4) — RULEBOOK R2.1, R2.2, R2.6"
    type: sum
    sql: ${TABLE}.total_poblacion ;;
    filters: [dim_edad.edad_anno_anno: "0 to 4"]
    value_format_name: decimal_0
    view_label: "Medidas"
    hidden: yes
  }
  measure: personas_sexo_6_edad_15_49 {
    # R2 helper — used by `Índice de maternidad`.
    # R2.6 naming; R2.4 keeps this separate from any semantically equal condition
    # written differently in the RPD, so every measure traces to one ExprTextDesc.
    description: "FILTER(Personas USING Sexo (código) = '6' AND Edad (año a año) BETWEEN 15 AND 49) — RULEBOOK R2.1, R2.2, R2.6"
    type: sum
    sql: ${TABLE}.total_poblacion ;;
    filters: [dim_sexo.sexo_codigo: "6", dim_edad.edad_anno_anno: "15 to 49"]
    value_format_name: decimal_0
    view_label: "Medidas"
    hidden: yes
  }
  measure: personas_sexo_6_edad_20_34 {
    # R2 helper — used by `Índice de potencialidad`.
    # R2.6 naming; R2.4 keeps this separate from any semantically equal condition
    # written differently in the RPD, so every measure traces to one ExprTextDesc.
    description: "FILTER(Personas USING Sexo (código) = '6' AND Edad (año a año) BETWEEN 20 AND 34) — RULEBOOK R2.1, R2.2, R2.6"
    type: sum
    sql: ${TABLE}.total_poblacion ;;
    filters: [dim_sexo.sexo_codigo: "6", dim_edad.edad_anno_anno: "20 to 34"]
    value_format_name: decimal_0
    view_label: "Medidas"
    hidden: yes
  }
  measure: personas_sexo_6_edad_35_49 {
    # R2 helper — used by `Índice de potencialidad`.
    # R2.6 naming; R2.4 keeps this separate from any semantically equal condition
    # written differently in the RPD, so every measure traces to one ExprTextDesc.
    description: "FILTER(Personas USING Sexo (código) = '6' AND Edad (año a año) BETWEEN 35 AND 49) — RULEBOOK R2.1, R2.2, R2.6"
    type: sum
    sql: ${TABLE}.total_poblacion ;;
    filters: [dim_sexo.sexo_codigo: "6", dim_edad.edad_anno_anno: "35 to 49"]
    value_format_name: decimal_0
    view_label: "Medidas"
    hidden: yes
  }
  measure: personas_pais_not_108 {
    # R2 helper — used by `Porcentaje población extranjera`, `Personas nacionalidad extranjera`.
    # R2.6 naming; R2.4 keeps this separate from any semantically equal condition
    # written differently in the RPD, so every measure traces to one ExprTextDesc.
    description: "FILTER(Personas USING Nacionalidad país código <> '108') — RULEBOOK R2.1, R2.2, R2.6"
    type: sum
    sql: ${TABLE}.total_poblacion ;;
    filters: [dim_pais.nacionalidad_pais_codigo: "-108"]
    value_format_name: decimal_0
    view_label: "Medidas"
    hidden: yes
  }
}
