# Generated by tools/gen_lookml.py from migration/ir/model.json.
# Do not edit by hand; edit the generator or the IR.
# Governed by docs/RULEBOOK.md — R6 (joins), R8.5 (view labels).

connection: "@{connection_name}"

include: "/views/**/*.view.lkml"

include: "/dashboards/*.dashboard.lookml"

explore: censo_anual {
  view_name: fct_censo_anual
  label: "Censo Anual"
  view_label: "Censo Anual"
  description: "Censo anual de población de Aragón. Port of OBIEE subject area TEST_LOOKER (presentation alias “Censo Anual”), read from OBIEE/modelo_semantico/XML_DMS. Grain: one row per anno_censo, dim_pais_nacionalidad, dim_territorio_residencia, dim_sexo, dim_edad."
  # Fanout guard — R6.2. It is NOT in this file. The guard is `primary_key:
  # yes` on each dimension's key in views/dim_*.view.lkml: that is what lets
  # Looker skip symmetric aggregates. The `relationship: many_to_one` lines
  # below only declare the shape. If SUM(Personas) stops reconciling to
  # 6,717,654, check those primary_key declarations before touching anything here.
  join: dim_pais {
    # Dim Pais Nacionalidad Censo Anual — RPD multiplicity n..n → 0..1, type=Inner (R6.1, R6.3).
    # Key from PhysicalForeignKey dim_pais_nacionalidad → pais_clave (R6.4).
    view_label: "Nacionalidad"
    type: inner
    sql_on: ${fct_censo_anual.dim_pais_nacionalidad} = ${dim_pais.pais_clave} ;;
    relationship: many_to_one
  }
  join: dim_edad {
    # Dim Edad Censo Anual — RPD multiplicity n..n → 0..1, type=Inner (R6.1, R6.3).
    # Key from PhysicalForeignKey dim_edad → dimension_key (R6.4).
    view_label: "Edad y Sexo"
    type: inner
    sql_on: ${fct_censo_anual.dim_edad} = ${dim_edad.dimension_key} ;;
    relationship: many_to_one
  }
  join: dim_territorio {
    # Dim Territorio Residencia Censo Anual — RPD multiplicity n..n → 0..1, type=Inner (R6.1, R6.3).
    # Key from PhysicalForeignKey dim_territorio_residencia → dimension_key (R6.4).
    view_label: "Lugar de Residencia"
    type: inner
    sql_on: ${fct_censo_anual.dim_territorio_residencia} = ${dim_territorio.dimension_key} ;;
    relationship: many_to_one
  }
  join: dim_sexo {
    # Dim Sexo Censo Anual — RPD multiplicity n..n → 0..1, type=Inner (R6.1, R6.3).
    # Key from PhysicalForeignKey dim_sexo → dimension_key (R6.4).
    view_label: "Edad y Sexo"
    type: inner
    sql_on: ${fct_censo_anual.dim_sexo} = ${dim_sexo.dimension_key} ;;
    relationship: many_to_one
  }
}
